### PR TITLE
Fix typo in connector log

### PR DESCRIPTION
**Pull request by viveksyngh**
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
Approved

**Comment by alexellis** [comment]
How has this been tested?

**Comment by viveksyngh** [comment]
This has been tested on local cluster with k3d and my development image for nats connector `viveksyngh/nats-connector:latest-dev`


```
kubectl logs -f pod/nats-connector-75fdc8ffdd-9gmpj -n openfaas 
==============================================================================
NATS Connector for OpenFaaS

Gateway URL: http://gateway.openfaas:8080
NATS URL: nats://nats:4222
Topics: [nats-test]
Upstream timeout: 1m1s
Topic-map rebuild interval: 5s
Async invocation: "false"
==============================================================================

2020/05/02 13:13:38 Configured topics: [nats-test]
2020/05/02 13:13:38 Binding to topic: "nats-test"
2020/05/02 13:13:38 Subscription: nats-test ready
```

**Comment by alexellis** [comment]
Thank you for adding the output. If no issue is provided and no evidence of testing then it makes it very hard to merge.

**Pull request merged**
