### PR TITLE
Add test functions and instructions to verify installation

### LINKED ISSUE #4: Add example Pod to publish some tester messages
## Description

There is no way included with the repo to test this connector, create a Go application and an example Pod that will publish some test messages. An OpenFaaS function using the classic Go template would also be fine. 

Also change faas-request to another topic (nats-test?) so that it doesn't clash with the built-in NATS Streaming topic.

Update the README with how to test / use the connector.

Other connectors with examples:

* https://github.com/openfaas-incubator/kafka-connector/
* https://github.com/openfaas-incubator/openfaas-vcenter-connector

This should be an absolute minimal example, simply to publish the input on the topic.

### PR DESCRIPTION
**Pull request by LucasRoesler**
**What**
- Add test publisher and receiver functions and instructions for how to
  use them to test the installations of the `nats-connector`. This
  should make the installation easier for users.

@alexellis the test functions will need to be built and pushed to the OpenFaaS Docker Hub

Resolves #4

### CODE REVIEW

**Comment by alexellis** [comment]
Do you need to commit the vendor folder when using modules?

**Comment by LucasRoesler** [comment]
@alexellis i left them there because i thought it would be easier than documenting the requirement to use `-b GO111MODULE=on` during `faas-cli build`. The stack file doesn't support build args yet you have to pass the build arg to use go modules in the template.  That is why i created some new templates for my personal use, but i figured you would not want that included here.

**Comment by alexellis** [comment]
Thanks for simplifying the example :+1: 

Given that the OpenFaaS contributing guide asks for `dep` still, I was surprised to see go modules used anyway. I guess we can leave it as is.

The user will be running bespoke commands for testing this, so I don't think using --build-arg is a problem.

**Comment by alexellis** [comment]
I'm running `faas-cli build/push` for the images as requested.

**Comment by alexellis** [comment]
The images are up now :+1:

**Pull request merged**
